cluster:
  name: enterprise-sim
  workers: 3
  registry_port: 5001
  api_port: 6443
  ingress_http_port: 80
  ingress_https_port: 443
  volume_mounts:
    - ./.enterprise-sim/storage:/var/openebs

services:
  istio:
    enabled: true
    version: "1.19.0"
    config: {}

  cert-manager:
    enabled: true
    version: "v1.17.1"
    config: {}

  storage:
    enabled: true
    version: "latest"
    config: {}

  minio:
    enabled: true
    version: "7.1.1"
    config:
      storage_size: "10Gi"
      replicas: 1

  sample-app:
    enabled: true
    version: "latest"
    config:
      app_name: "hello-app"
      region: "ap"

environment:
  domain: "local.butterflycluster.com"

regions:
  - us
  - eu
  - ap
