# Istio DestinationRule for mTLS enforcement and load balancing
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ${APP_NAME}-dr
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    compliance.region: ${REGION}
spec:
  host: ${APP_NAME}.${NAMESPACE}.svc.cluster.local
  trafficPolicy:
    # Enable mTLS for strict mode
    tls:
      mode: ISTIO_MUTUAL
    # Load balancing and circuit breaker settings
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
