apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    compliance.region: ${REGION}
    # Compliance labels for automatic routing via enterprise-sim.sh routes reconcile
    compliance.routing/enabled: "true"
  annotations:
    # Service mesh annotations
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  # If using AWS
spec:
  type: ClusterIP
  selector:
    app: ${APP_NAME}
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
