apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $certificate_name
  namespace: istio-system
spec:
  secretName: $certificate_name
  issuerRef:
    name: $issuer_name
    kind: ClusterIssuer
  dnsNames:
  - "$domain"
  - "*.$domain"
